runtime: python311
instance_class: F1

entrypoint: gunicorn -b :$PORT app:app

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto

env_variables:
  # Database Credentials
  DB_USER: "appsadmin"
  DB_PASS: "appsadmin2025"
  DB_HOST: "34.93.75.171"
  DB_PORT: "3306"

  # Database Names
  TGT_DB: "InSolvo_Documents"
  DB_NAME: "elicita"
  DATABASE_NAME: "mc"
  DATABASE_NAME_A: "elicita"

  # Flask Secret Key
  SECRET_KEY: "vasanth"

  # SMTP Mail Credentials
  SMTP_SERVER: "smtp.datasolve-analytics.com"
  SMTP_PORT: "587"
  WEBMAIL_USER: "apps.admin@datasolve-analytics.com"
  WEBMAIL_PASSWORD: "datasolve@2025"
