# app.yaml
runtime: python311  # Unga Python version
instance_class: F1

# Gunicorn entrypoint (unga file app.py, Flask variable 'app')
entrypoint: gunicorn -b :$PORT app:app

# Static files handling (unga 'static' folder ku)
handlers:
- url: /static
  static_dir: static

# All other routes
- url: /.*
  script: auto

# Environment variables (Indha 'secrets' ellaam inga thaan varanum)
env_variables:
  # Database Credentials
  DB_USER: 'appsadmin'
  DB_PASS: 'appsadmin2025'
  DB_HOST: '34.93.75.171'
  DB_PORT: '3306'
  
  # Database Names
  TGT_DB: 'InSolvo_Documents'
  DB_NAME: 'elicita'
  DATABASE_NAME: 'mc'
  DATABASE_NAME_A: 'elicita'

  # Flask Secret Key
  SECRET_KEY: 'vasanth' # Idhukku 'vasanth' nu vekradhukku badhila, oru complex key generate panni podunga

  # SMTP Mail Credentials
  SMTP_SERVER: "smtp.datasolve-analytics.com"
  SMTP_PORT: "587"
  WEBMAIL_USER: "apps.admin@datasolve-analytics.com"
  WEBMAIL_PASSWORD: "datasolve@2025"